### PR TITLE
First stab at what new interface for discovery might look like

### PR DESCRIPTION
**Pull request by fabianvf**
@asetty Rough idea of what I was thinking

### CODE REVIEW

**Comment by asetty** [comment]
Cool let's move the conversation to here then :)

Copied from the other conversation:
One thing that comes to mind, is that the default would need to be the completely lazy loading so we don't need to make changes in ansible and I'm not sure if that's the right way to go or not. LMK what you think / if I'm missing something.

**Comment by fabianvf** [comment]
I think lazy is a better default, as long as we make sure we always return what eager would return.

**Comment by asetty** [comment]
SGTM thanks for posting the start of this

**Comment by asetty** [comment]
I've been super busy the past week and a half so haven't had a chance to get started on this. Have looked at the code a bit, but need a bit more understanding of kubernetes API on my end to implement lazy loading correctly.

Any update on your end? Also could we maybe set up a meeting (30 min maybe) to chat?
Email: asetty@arista.com

**Comment by fabianvf** [comment]
@asetty no worries, I'm in meetings all week long but I'll try and set up a meeting for early next week.

**Pull request closed without merging**
