### PR TITLE
Rename async to async_req for compatibility with python3 and kubernetes 7

### LINKED ISSUE #183: Python3.7 compatibility: async is a reserved keyword
Hi all, 

While trying to import the library with python3.7, the following error occurs:

```
  File "/virtualenv/lib/python3.7/site-packages/openshift/__init__.py", line 15, in <module>
    import openshift.client
  File "/virtualenv/lib/python3.7/site-packages/openshift/client/__init__.py", line 221, in <module>
    from .apis.apps_openshift_io_api import AppsOpenshiftIoApi
  File "/virtualenv/lib/python3.7/site-packages/openshift/client/apis/__init__.py", line 4, in <module>
    from .apps_openshift_io_api import AppsOpenshiftIoApi
  File "/virtualenv/lib/python3.7/site-packages/openshift/client/apis/apps_openshift_io_api.py", line 120
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
```

This has already been fixed in the upstream here https://github.com/kubernetes-client/python/pull/568.

### PR DESCRIPTION
**Pull request by fabianvf**
fixes #183 

This PR will break backwards compatibility

### CODE REVIEW

**Comment by fabianvf** [comment]
ping @Chive @pvdvreede

**Comment by willthames** [comment]
These tests appear to be timing out rather than failing. Not sure if they need breaking up or profiling or some travis configuration to allow them to take longer

**Comment by yboaron** [comment]
I'd tested this PR with Kubernetes client 7.0.0 , and it's working!
I'm not getting [1] error anymore. 

[1]  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 58, in __init__
    self._load_server_info()
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 62, in _load_server_info
    self.__version = {'kubernetes': load_json(self.request('get', '/version'))}
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 255, in request
    _return_http_data_only=params.get('_return_http_data_only', True)
TypeError: call_api() got an unexpected keyword argument 'async'

**Comment by willthames** [comment]
I've also run the updated ansible k8s test suite from ansible/ansible#44821 and it passes

**Pull request merged**
