### PR TITLE
Fix kubernetes EagerDiscoverer import

### PR DESCRIPTION
**Pull request by aaguirreRH**

### CODE REVIEW

**Comment by HonakerM** [comment]
@aaguirreRH any movement on this PR? I ran into the same issue

**Comment by aaguirreRH** [comment]
@HonakerM I detected the issue by chance and submitted this PR, but no movement since then...

**Comment by HonakerM** [comment]
@aaguirreRH anyway I can help with that linting error? I'd love to get this merged. Thank you for finding the issue!

**Review by fabianvf — APPROVED** [review]

**Pull request merged**
