### PR TITLE
Remove md5, which fails in FIPS environment

### PR DESCRIPTION
**Pull request by asmacdo**

### CODE REVIEW

**Comment by jmrodri** [comment]
for posterity, I verified this change will fix the problem:
```python
>> import hashlib
>>> hashlib.md5("foobar").hexdigest()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
>>> hashlib.sha1("foobar").hexdigest()
'8843d7f92416211de9ebb963ff4ce28125932878'
>>> 
```

**Comment by jmrodri** [comment]
Built a new ansible-operator base image and build a new ansible-service-broker-operator image as well.

* This is the change on the deployed image.
```
[jesusr@transam ansible-service-broker{master}]$ oc rsh ansible-service-broker-operator-597f8455bf-tlccz
sh-4.2$ cd /usr/local/lib/python3.6/site-packages/openshift/dynamic
sh-4.2$ grep -n hashlib client.py 
7:import hashlib
104:        default_cachefile_name = 'osrcp-{0}.json'.format(hashlib.sha1(self.__get_default_cache_id()).hexdigest())
sh-4.2$ 
```

* Broker has been deployed
```
[jesusr@transam ansible-service-broker{master}]$ oc get pods
NAME                                               READY   STATUS      RESTARTS   AGE
ansible-service-broker-operator-597f8455bf-tlccz   1/1     Running     0          17m
asb-1-2rvdp                                        2/2     Running     0          14m
asb-1-deploy                                       0/1     Completed   0          15m
```

* Broker came up fine
```
time="2019-12-06T02:03:54Z" level=info msg="update spec: 60836f0ce3bd7d325587211dd7791f5b|dh-import-vm-apb to crd"
time="2019-12-06T02:03:55Z" level=info msg="update spec: f755257efed3e3d43c8b82afd0db1181|dh-prometheus-apb to crd"
time="2019-12-06T02:03:55Z" level=info msg="Broker successfully bootstrapped"
```

**Comment by jwforres** [comment]
merging as requested

**Pull request merged**
