### PR TITLE
user/password login support

### PR DESCRIPTION
**Pull request by pbertera**
This PR adds an helper implementing the user/password authentication.
Usage example added to the README

### CODE REVIEW

**Comment by fabianvf** [comment]
oh wow I missed this, this is awesome!

**Comment by fabianvf** [comment]
Would it be possible to add a test (pretty much the code snippet you added would be fine)? If that's too much I can just merge and add it myself

**Comment by pbertera** [comment]
Hi Fabian, thanks for looking into that. Honestly I do not know how to create a test requiring credentials to authenticate..

**Comment by fabianvf** [comment]
@pbertera no problem I can add it myself (might take a bit to find the time). Just for reference, I've done a similar sort of test for the community.okd modules, what I did there was create a htpasswd auth user (https://github.com/openshift/community.okd/blob/main/molecule/default/prepare.yml#L19-L60), then logged in as that user (https://github.com/openshift/community.okd/blob/main/molecule/default/tasks/openshift_auth.yml#L3-L31)

**Pull request merged**
